# Generated by Django 5.2.1 on 2025-05-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='public_s3_image_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
